package com.capital11.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "customer")
public class Customer {

    /** Assigned by the application (random, as in the legacy app), not generated by the database. */
    @Id
    @Column(name = "cid")
    private Integer cid;

    @Column(name = "name", nullable = false)
    private String name;

    @Column(name = "email", nullable = false)
    private String email;

    @Column(name = "username", nullable = false, unique = true)
    private String username;

    @Column(name = "password", nullable = false)
    private String password;

    @Column(name = "birthday")
    private String birthday;

    @Column(name = "gender")
    private String gender;

    protected Customer() {
    }

    public Customer(Integer cid, String name, String email, String username, String password,
                    String birthday, String gender) {
        this.cid = cid;
        this.name = name;
        this.email = email;
        this.username = username;
        this.password = password;
        this.birthday = birthday;
        this.gender = gender;
    }

    public Integer getCid() {
        return cid;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getBirthday() {
        return birthday;
    }

    public String getGender() {
        return gender;
    }
}
